// Code generated by MockGen. DO NOT EDIT.
// Source: limit_checker.go
//
// Generated by this command:
//
//	mockgen -source=limit_checker.go -destination=limit_checker_mock.go -package=query
//

// Package query is a generated GoMock package.
package query

import (
	context "context"
	reflect "reflect"
	model "tracer/pkg/model"

	gomock "go.uber.org/mock/gomock"
)

// MockLimitChecker is a mock of LimitChecker interface.
type MockLimitChecker struct {
	ctrl     *gomock.Controller
	recorder *MockLimitCheckerMockRecorder
	isgomock struct{}
}

// MockLimitCheckerMockRecorder is the mock recorder for MockLimitChecker.
type MockLimitCheckerMockRecorder struct {
	mock *MockLimitChecker
}

// NewMockLimitChecker creates a new mock instance.
func NewMockLimitChecker(ctrl *gomock.Controller) *MockLimitChecker {
	mock := &MockLimitChecker{ctrl: ctrl}
	mock.recorder = &MockLimitCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimitChecker) EXPECT() *MockLimitCheckerMockRecorder {
	return m.recorder
}

// CheckLimits mocks base method.
func (m *MockLimitChecker) CheckLimits(ctx context.Context, input *model.CheckLimitsInput) (*model.CheckLimitsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLimits", ctx, input)
	ret0, _ := ret[0].(*model.CheckLimitsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLimits indicates an expected call of CheckLimits.
func (mr *MockLimitCheckerMockRecorder) CheckLimits(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLimits", reflect.TypeOf((*MockLimitChecker)(nil).CheckLimits), ctx, input)
}

// RollbackUsage mocks base method.
func (m *MockLimitChecker) RollbackUsage(ctx context.Context, input *model.CheckLimitsInput, usageDetails []model.LimitUsageDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackUsage", ctx, input, usageDetails)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackUsage indicates an expected call of RollbackUsage.
func (mr *MockLimitCheckerMockRecorder) RollbackUsage(ctx, input, usageDetails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackUsage", reflect.TypeOf((*MockLimitChecker)(nil).RollbackUsage), ctx, input, usageDetails)
}
