// Code generated by MockGen. DO NOT EDIT.
// Source: usage_counter_repository.go
//
// Generated by this command:
//
//	mockgen -source=usage_counter_repository.go -destination=usage_counter_repository_mock.go -package=query
//

// Package query is a generated GoMock package.
package query

import (
	context "context"
	reflect "reflect"
	time "time"
	model "tracer/pkg/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUsageCounterRepository is a mock of UsageCounterRepository interface.
type MockUsageCounterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUsageCounterRepositoryMockRecorder
	isgomock struct{}
}

// MockUsageCounterRepositoryMockRecorder is the mock recorder for MockUsageCounterRepository.
type MockUsageCounterRepositoryMockRecorder struct {
	mock *MockUsageCounterRepository
}

// NewMockUsageCounterRepository creates a new mock instance.
func NewMockUsageCounterRepository(ctrl *gomock.Controller) *MockUsageCounterRepository {
	mock := &MockUsageCounterRepository{ctrl: ctrl}
	mock.recorder = &MockUsageCounterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageCounterRepository) EXPECT() *MockUsageCounterRepositoryMockRecorder {
	return m.recorder
}

// DecrementAtomic mocks base method.
func (m *MockUsageCounterRepository) DecrementAtomic(ctx context.Context, counterID uuid.UUID, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementAtomic", ctx, counterID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementAtomic indicates an expected call of DecrementAtomic.
func (mr *MockUsageCounterRepositoryMockRecorder) DecrementAtomic(ctx, counterID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementAtomic", reflect.TypeOf((*MockUsageCounterRepository)(nil).DecrementAtomic), ctx, counterID, amount)
}

// DeleteExpiredCounters mocks base method.
func (m *MockUsageCounterRepository) DeleteExpiredCounters(ctx context.Context, olderThan time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredCounters", ctx, olderThan)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredCounters indicates an expected call of DeleteExpiredCounters.
func (mr *MockUsageCounterRepositoryMockRecorder) DeleteExpiredCounters(ctx, olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredCounters", reflect.TypeOf((*MockUsageCounterRepository)(nil).DeleteExpiredCounters), ctx, olderThan)
}

// GetByLimitID mocks base method.
func (m *MockUsageCounterRepository) GetByLimitID(ctx context.Context, limitID uuid.UUID) ([]model.UsageCounter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLimitID", ctx, limitID)
	ret0, _ := ret[0].([]model.UsageCounter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLimitID indicates an expected call of GetByLimitID.
func (mr *MockUsageCounterRepositoryMockRecorder) GetByLimitID(ctx, limitID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLimitID", reflect.TypeOf((*MockUsageCounterRepository)(nil).GetByLimitID), ctx, limitID)
}

// GetForUpdate mocks base method.
func (m *MockUsageCounterRepository) GetForUpdate(ctx context.Context, limitID uuid.UUID, scopeKey, periodKey string) (*model.UsageCounter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForUpdate", ctx, limitID, scopeKey, periodKey)
	ret0, _ := ret[0].(*model.UsageCounter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForUpdate indicates an expected call of GetForUpdate.
func (mr *MockUsageCounterRepositoryMockRecorder) GetForUpdate(ctx, limitID, scopeKey, periodKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForUpdate", reflect.TypeOf((*MockUsageCounterRepository)(nil).GetForUpdate), ctx, limitID, scopeKey, periodKey)
}

// GetOrCreateForUpdate mocks base method.
func (m *MockUsageCounterRepository) GetOrCreateForUpdate(ctx context.Context, limitID uuid.UUID, scopeKey, periodKey string) (*model.UsageCounter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateForUpdate", ctx, limitID, scopeKey, periodKey)
	ret0, _ := ret[0].(*model.UsageCounter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateForUpdate indicates an expected call of GetOrCreateForUpdate.
func (mr *MockUsageCounterRepositoryMockRecorder) GetOrCreateForUpdate(ctx, limitID, scopeKey, periodKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateForUpdate", reflect.TypeOf((*MockUsageCounterRepository)(nil).GetOrCreateForUpdate), ctx, limitID, scopeKey, periodKey)
}

// GetUsageForLimits mocks base method.
func (m *MockUsageCounterRepository) GetUsageForLimits(ctx context.Context, limitIDs []uuid.UUID, scopeKey, periodKey string) (map[uuid.UUID]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsageForLimits", ctx, limitIDs, scopeKey, periodKey)
	ret0, _ := ret[0].(map[uuid.UUID]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsageForLimits indicates an expected call of GetUsageForLimits.
func (mr *MockUsageCounterRepositoryMockRecorder) GetUsageForLimits(ctx, limitIDs, scopeKey, periodKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsageForLimits", reflect.TypeOf((*MockUsageCounterRepository)(nil).GetUsageForLimits), ctx, limitIDs, scopeKey, periodKey)
}

// IncrementAtomic mocks base method.
func (m *MockUsageCounterRepository) IncrementAtomic(ctx context.Context, counterID uuid.UUID, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAtomic", ctx, counterID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementAtomic indicates an expected call of IncrementAtomic.
func (mr *MockUsageCounterRepositoryMockRecorder) IncrementAtomic(ctx, counterID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAtomic", reflect.TypeOf((*MockUsageCounterRepository)(nil).IncrementAtomic), ctx, counterID, amount)
}
