// Code generated by MockGen. DO NOT EDIT.
// Source: limit_repository.go
//
// Generated by this command:
//
//	mockgen -source=limit_repository.go -destination=limit_repository_mock.go -package=command
//

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"
	time "time"
	model "tracer/pkg/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockLimitRepository is a mock of LimitRepository interface.
type MockLimitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLimitRepositoryMockRecorder
	isgomock struct{}
}

// MockLimitRepositoryMockRecorder is the mock recorder for MockLimitRepository.
type MockLimitRepositoryMockRecorder struct {
	mock *MockLimitRepository
}

// NewMockLimitRepository creates a new mock instance.
func NewMockLimitRepository(ctrl *gomock.Controller) *MockLimitRepository {
	mock := &MockLimitRepository{ctrl: ctrl}
	mock.recorder = &MockLimitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimitRepository) EXPECT() *MockLimitRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLimitRepository) Create(ctx context.Context, lmt *model.Limit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, lmt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLimitRepositoryMockRecorder) Create(ctx, lmt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLimitRepository)(nil).Create), ctx, lmt)
}

// GetByID mocks base method.
func (m *MockLimitRepository) GetByID(ctx context.Context, limitID uuid.UUID) (*model.Limit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, limitID)
	ret0, _ := ret[0].(*model.Limit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLimitRepositoryMockRecorder) GetByID(ctx, limitID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLimitRepository)(nil).GetByID), ctx, limitID)
}

// Update mocks base method.
func (m *MockLimitRepository) Update(ctx context.Context, lmt *model.Limit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, lmt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLimitRepositoryMockRecorder) Update(ctx, lmt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLimitRepository)(nil).Update), ctx, lmt)
}

// UpdateStatus mocks base method.
func (m *MockLimitRepository) UpdateStatus(ctx context.Context, limitID uuid.UUID, status model.LimitStatus, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, limitID, status, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockLimitRepositoryMockRecorder) UpdateStatus(ctx, limitID, status, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockLimitRepository)(nil).UpdateStatus), ctx, limitID, status, updatedAt)
}
