// Code generated by MockGen. DO NOT EDIT.
// Source: rule_cache_writer.go
//
// Generated by this command:
//
//	mockgen -source=rule_cache_writer.go -destination=rule_cache_writer_mock.go -package=command
//

// Package command is a generated GoMock package.
package command

import (
	reflect "reflect"
	model "tracer/pkg/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRuleCacheWriter is a mock of RuleCacheWriter interface.
type MockRuleCacheWriter struct {
	ctrl     *gomock.Controller
	recorder *MockRuleCacheWriterMockRecorder
	isgomock struct{}
}

// MockRuleCacheWriterMockRecorder is the mock recorder for MockRuleCacheWriter.
type MockRuleCacheWriterMockRecorder struct {
	mock *MockRuleCacheWriter
}

// NewMockRuleCacheWriter creates a new mock instance.
func NewMockRuleCacheWriter(ctrl *gomock.Controller) *MockRuleCacheWriter {
	mock := &MockRuleCacheWriter{ctrl: ctrl}
	mock.recorder = &MockRuleCacheWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleCacheWriter) EXPECT() *MockRuleCacheWriterMockRecorder {
	return m.recorder
}

// RemoveRule mocks base method.
func (m *MockRuleCacheWriter) RemoveRule(id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveRule", id)
}

// RemoveRule indicates an expected call of RemoveRule.
func (mr *MockRuleCacheWriterMockRecorder) RemoveRule(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRule", reflect.TypeOf((*MockRuleCacheWriter)(nil).RemoveRule), id)
}

// UpsertRule mocks base method.
func (m *MockRuleCacheWriter) UpsertRule(rule *model.Rule, program any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpsertRule", rule, program)
}

// UpsertRule indicates an expected call of UpsertRule.
func (mr *MockRuleCacheWriterMockRecorder) UpsertRule(rule, program any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRule", reflect.TypeOf((*MockRuleCacheWriter)(nil).UpsertRule), rule, program)
}
