// Code generated by MockGen. DO NOT EDIT.
// Source: health.go
//
// Generated by this command:
//
//	mockgen -source=health.go -destination=health_mock.go -package=in
//

// Package in is a generated GoMock package.
package in

import (
	sql "database/sql"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRuleCacheHealthProvider is a mock of RuleCacheHealthProvider interface.
type MockRuleCacheHealthProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRuleCacheHealthProviderMockRecorder
	isgomock struct{}
}

// MockRuleCacheHealthProviderMockRecorder is the mock recorder for MockRuleCacheHealthProvider.
type MockRuleCacheHealthProviderMockRecorder struct {
	mock *MockRuleCacheHealthProvider
}

// NewMockRuleCacheHealthProvider creates a new mock instance.
func NewMockRuleCacheHealthProvider(ctrl *gomock.Controller) *MockRuleCacheHealthProvider {
	mock := &MockRuleCacheHealthProvider{ctrl: ctrl}
	mock.recorder = &MockRuleCacheHealthProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleCacheHealthProvider) EXPECT() *MockRuleCacheHealthProviderMockRecorder {
	return m.recorder
}

// IsReady mocks base method.
func (m *MockRuleCacheHealthProvider) IsReady() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReady")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReady indicates an expected call of IsReady.
func (mr *MockRuleCacheHealthProviderMockRecorder) IsReady() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReady", reflect.TypeOf((*MockRuleCacheHealthProvider)(nil).IsReady))
}

// Size mocks base method.
func (m *MockRuleCacheHealthProvider) Size() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *MockRuleCacheHealthProviderMockRecorder) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockRuleCacheHealthProvider)(nil).Size))
}

// Staleness mocks base method.
func (m *MockRuleCacheHealthProvider) Staleness() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Staleness")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Staleness indicates an expected call of Staleness.
func (mr *MockRuleCacheHealthProviderMockRecorder) Staleness() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Staleness", reflect.TypeOf((*MockRuleCacheHealthProvider)(nil).Staleness))
}

// MockPostgresDBProvider is a mock of PostgresDBProvider interface.
type MockPostgresDBProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresDBProviderMockRecorder
	isgomock struct{}
}

// MockPostgresDBProviderMockRecorder is the mock recorder for MockPostgresDBProvider.
type MockPostgresDBProviderMockRecorder struct {
	mock *MockPostgresDBProvider
}

// NewMockPostgresDBProvider creates a new mock instance.
func NewMockPostgresDBProvider(ctrl *gomock.Controller) *MockPostgresDBProvider {
	mock := &MockPostgresDBProvider{ctrl: ctrl}
	mock.recorder = &MockPostgresDBProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgresDBProvider) EXPECT() *MockPostgresDBProviderMockRecorder {
	return m.recorder
}

// GetDB mocks base method.
func (m *MockPostgresDBProvider) GetDB() (*sql.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sql.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDB indicates an expected call of GetDB.
func (mr *MockPostgresDBProviderMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockPostgresDBProvider)(nil).GetDB))
}

// IsConnected mocks base method.
func (m *MockPostgresDBProvider) IsConnected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConnected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConnected indicates an expected call of IsConnected.
func (mr *MockPostgresDBProviderMockRecorder) IsConnected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnected", reflect.TypeOf((*MockPostgresDBProvider)(nil).IsConnected))
}
