// Code generated by MockGen. DO NOT EDIT.
// Source: health.go
//
// Generated by this command:
//
//	mockgen -source=health.go -destination=health_mock.go -package=in
//

// Package in is a generated GoMock package.
package in

import (
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPostgresDBProvider is a mock of PostgresDBProvider interface.
type MockPostgresDBProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresDBProviderMockRecorder
	isgomock struct{}
}

// MockPostgresDBProviderMockRecorder is the mock recorder for MockPostgresDBProvider.
type MockPostgresDBProviderMockRecorder struct {
	mock *MockPostgresDBProvider
}

// NewMockPostgresDBProvider creates a new mock instance.
func NewMockPostgresDBProvider(ctrl *gomock.Controller) *MockPostgresDBProvider {
	mock := &MockPostgresDBProvider{ctrl: ctrl}
	mock.recorder = &MockPostgresDBProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgresDBProvider) EXPECT() *MockPostgresDBProviderMockRecorder {
	return m.recorder
}

// GetDB mocks base method.
func (m *MockPostgresDBProvider) GetDB() (*sql.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sql.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDB indicates an expected call of GetDB.
func (mr *MockPostgresDBProviderMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockPostgresDBProvider)(nil).GetDB))
}

// IsConnected mocks base method.
func (m *MockPostgresDBProvider) IsConnected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConnected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConnected indicates an expected call of IsConnected.
func (mr *MockPostgresDBProviderMockRecorder) IsConnected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnected", reflect.TypeOf((*MockPostgresDBProvider)(nil).IsConnected))
}
