// Code generated by MockGen. DO NOT EDIT.
// Source: audit_writer.go
//
// Generated by this command:
//
//	mockgen -source=audit_writer.go -destination=mocks/audit_writer_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	db "tracer/internal/adapters/postgres/db"
	model "tracer/pkg/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditWriter is a mock of AuditWriter interface.
type MockAuditWriter struct {
	ctrl     *gomock.Controller
	recorder *MockAuditWriterMockRecorder
	isgomock struct{}
}

// MockAuditWriterMockRecorder is the mock recorder for MockAuditWriter.
type MockAuditWriterMockRecorder struct {
	mock *MockAuditWriter
}

// NewMockAuditWriter creates a new mock instance.
func NewMockAuditWriter(ctrl *gomock.Controller) *MockAuditWriter {
	mock := &MockAuditWriter{ctrl: ctrl}
	mock.recorder = &MockAuditWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditWriter) EXPECT() *MockAuditWriterMockRecorder {
	return m.recorder
}

// RecordLimitEvent mocks base method.
func (m *MockAuditWriter) RecordLimitEvent(ctx context.Context, eventType model.AuditEventType, action model.AuditAction, limitID uuid.UUID, before, after map[string]any, reason, clientIP string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordLimitEvent", ctx, eventType, action, limitID, before, after, reason, clientIP)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordLimitEvent indicates an expected call of RecordLimitEvent.
func (mr *MockAuditWriterMockRecorder) RecordLimitEvent(ctx, eventType, action, limitID, before, after, reason, clientIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordLimitEvent", reflect.TypeOf((*MockAuditWriter)(nil).RecordLimitEvent), ctx, eventType, action, limitID, before, after, reason, clientIP)
}

// RecordRuleEvent mocks base method.
func (m *MockAuditWriter) RecordRuleEvent(ctx context.Context, eventType model.AuditEventType, action model.AuditAction, ruleID uuid.UUID, before, after map[string]any, reason, clientIP string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordRuleEvent", ctx, eventType, action, ruleID, before, after, reason, clientIP)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordRuleEvent indicates an expected call of RecordRuleEvent.
func (mr *MockAuditWriterMockRecorder) RecordRuleEvent(ctx, eventType, action, ruleID, before, after, reason, clientIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRuleEvent", reflect.TypeOf((*MockAuditWriter)(nil).RecordRuleEvent), ctx, eventType, action, ruleID, before, after, reason, clientIP)
}

// RecordValidationEvent mocks base method.
func (m *MockAuditWriter) RecordValidationEvent(ctx context.Context, validationID uuid.UUID, request map[string]any, evalResult model.EvaluationResult, responseContext model.ValidationResponseContext, clientIP string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordValidationEvent", ctx, validationID, request, evalResult, responseContext, clientIP)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordValidationEvent indicates an expected call of RecordValidationEvent.
func (mr *MockAuditWriterMockRecorder) RecordValidationEvent(ctx, validationID, request, evalResult, responseContext, clientIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordValidationEvent", reflect.TypeOf((*MockAuditWriter)(nil).RecordValidationEvent), ctx, validationID, request, evalResult, responseContext, clientIP)
}

// RecordValidationEventWithTx mocks base method.
func (m *MockAuditWriter) RecordValidationEventWithTx(ctx context.Context, arg1 db.DB, validationID uuid.UUID, request map[string]any, evalResult model.EvaluationResult, responseContext model.ValidationResponseContext, clientIP string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordValidationEventWithTx", ctx, arg1, validationID, request, evalResult, responseContext, clientIP)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordValidationEventWithTx indicates an expected call of RecordValidationEventWithTx.
func (mr *MockAuditWriterMockRecorder) RecordValidationEventWithTx(ctx, arg1, validationID, request, evalResult, responseContext, clientIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordValidationEventWithTx", reflect.TypeOf((*MockAuditWriter)(nil).RecordValidationEventWithTx), ctx, arg1, validationID, request, evalResult, responseContext, clientIP)
}
