// Code generated by MockGen. DO NOT EDIT.
// Source: validation_service.go
//
// Generated by this command:
//
//	mockgen -source=validation_service.go -destination=mocks/validation_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "tracer/pkg/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRuleEvaluator is a mock of RuleEvaluator interface.
type MockRuleEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockRuleEvaluatorMockRecorder
	isgomock struct{}
}

// MockRuleEvaluatorMockRecorder is the mock recorder for MockRuleEvaluator.
type MockRuleEvaluatorMockRecorder struct {
	mock *MockRuleEvaluator
}

// NewMockRuleEvaluator creates a new mock instance.
func NewMockRuleEvaluator(ctrl *gomock.Controller) *MockRuleEvaluator {
	mock := &MockRuleEvaluator{ctrl: ctrl}
	mock.recorder = &MockRuleEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleEvaluator) EXPECT() *MockRuleEvaluatorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRuleEvaluator) Execute(ctx context.Context, req *model.ValidationRequest) (*model.EvaluationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(*model.EvaluationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockRuleEvaluatorMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRuleEvaluator)(nil).Execute), ctx, req)
}

// MockLimitChecker is a mock of LimitChecker interface.
type MockLimitChecker struct {
	ctrl     *gomock.Controller
	recorder *MockLimitCheckerMockRecorder
	isgomock struct{}
}

// MockLimitCheckerMockRecorder is the mock recorder for MockLimitChecker.
type MockLimitCheckerMockRecorder struct {
	mock *MockLimitChecker
}

// NewMockLimitChecker creates a new mock instance.
func NewMockLimitChecker(ctrl *gomock.Controller) *MockLimitChecker {
	mock := &MockLimitChecker{ctrl: ctrl}
	mock.recorder = &MockLimitCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimitChecker) EXPECT() *MockLimitCheckerMockRecorder {
	return m.recorder
}

// CheckLimits mocks base method.
func (m *MockLimitChecker) CheckLimits(ctx context.Context, input *model.CheckLimitsInput) (*model.CheckLimitsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLimits", ctx, input)
	ret0, _ := ret[0].(*model.CheckLimitsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLimits indicates an expected call of CheckLimits.
func (mr *MockLimitCheckerMockRecorder) CheckLimits(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLimits", reflect.TypeOf((*MockLimitChecker)(nil).CheckLimits), ctx, input)
}

// RollbackUsage mocks base method.
func (m *MockLimitChecker) RollbackUsage(ctx context.Context, input *model.CheckLimitsInput, usageDetails []model.LimitUsageDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackUsage", ctx, input, usageDetails)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackUsage indicates an expected call of RollbackUsage.
func (mr *MockLimitCheckerMockRecorder) RollbackUsage(ctx, input, usageDetails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackUsage", reflect.TypeOf((*MockLimitChecker)(nil).RollbackUsage), ctx, input, usageDetails)
}

// MockTransactionValidationQueryRepository is a mock of TransactionValidationQueryRepository interface.
type MockTransactionValidationQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionValidationQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionValidationQueryRepositoryMockRecorder is the mock recorder for MockTransactionValidationQueryRepository.
type MockTransactionValidationQueryRepositoryMockRecorder struct {
	mock *MockTransactionValidationQueryRepository
}

// NewMockTransactionValidationQueryRepository creates a new mock instance.
func NewMockTransactionValidationQueryRepository(ctrl *gomock.Controller) *MockTransactionValidationQueryRepository {
	mock := &MockTransactionValidationQueryRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionValidationQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionValidationQueryRepository) EXPECT() *MockTransactionValidationQueryRepositoryMockRecorder {
	return m.recorder
}

// FindByRequestID mocks base method.
func (m *MockTransactionValidationQueryRepository) FindByRequestID(ctx context.Context, requestID uuid.UUID) (*model.TransactionValidation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRequestID", ctx, requestID)
	ret0, _ := ret[0].(*model.TransactionValidation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRequestID indicates an expected call of FindByRequestID.
func (mr *MockTransactionValidationQueryRepositoryMockRecorder) FindByRequestID(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRequestID", reflect.TypeOf((*MockTransactionValidationQueryRepository)(nil).FindByRequestID), ctx, requestID)
}
