// Code generated by MockGen. DO NOT EDIT.
// Source: rule_sync_cache.go
//
// Generated by this command:
//
//	mockgen -source=rule_sync_cache.go -destination=mocks/rule_sync_cache_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"
	cache "tracer/internal/services/cache"
	model "tracer/pkg/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRuleSyncCache is a mock of RuleSyncCache interface.
type MockRuleSyncCache struct {
	ctrl     *gomock.Controller
	recorder *MockRuleSyncCacheMockRecorder
	isgomock struct{}
}

// MockRuleSyncCacheMockRecorder is the mock recorder for MockRuleSyncCache.
type MockRuleSyncCacheMockRecorder struct {
	mock *MockRuleSyncCache
}

// NewMockRuleSyncCache creates a new mock instance.
func NewMockRuleSyncCache(ctrl *gomock.Controller) *MockRuleSyncCache {
	mock := &MockRuleSyncCache{ctrl: ctrl}
	mock.recorder = &MockRuleSyncCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleSyncCache) EXPECT() *MockRuleSyncCacheMockRecorder {
	return m.recorder
}

// ApplyChanges mocks base method.
func (m *MockRuleSyncCache) ApplyChanges(upserts []*cache.CachedRule, removeIDs []uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ApplyChanges", upserts, removeIDs)
}

// ApplyChanges indicates an expected call of ApplyChanges.
func (mr *MockRuleSyncCacheMockRecorder) ApplyChanges(upserts, removeIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyChanges", reflect.TypeOf((*MockRuleSyncCache)(nil).ApplyChanges), upserts, removeIDs)
}

// GetActiveRules mocks base method.
func (m *MockRuleSyncCache) GetActiveRules(txScope *model.Scope) []*cache.CachedRule {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveRules", txScope)
	ret0, _ := ret[0].([]*cache.CachedRule)
	return ret0
}

// GetActiveRules indicates an expected call of GetActiveRules.
func (mr *MockRuleSyncCacheMockRecorder) GetActiveRules(txScope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveRules", reflect.TypeOf((*MockRuleSyncCache)(nil).GetActiveRules), txScope)
}

// LastSyncTime mocks base method.
func (m *MockRuleSyncCache) LastSyncTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastSyncTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// LastSyncTime indicates an expected call of LastSyncTime.
func (mr *MockRuleSyncCacheMockRecorder) LastSyncTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastSyncTime", reflect.TypeOf((*MockRuleSyncCache)(nil).LastSyncTime))
}

// Size mocks base method.
func (m *MockRuleSyncCache) Size() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *MockRuleSyncCacheMockRecorder) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockRuleSyncCache)(nil).Size))
}
